---

_sys_packages:
  default: []

  CentOS-7:
  - epel-release
  CentOS-8:
  - epel-release
  Ubuntu:
  - python3

_tls_packages:
  default: []

  CentOS-7:
  - python-cryptography
  - pyOpenSSL
  - openssh
  - openssl

  CentOS-8:
  - python3-cryptography
  - python3-pyOpenSSL
  - openssh
  - openssl

  Ubuntu:
  - python3-cryptography
  - python3-openssl
  - openssh-client
  - openssl

_jdk_packages:
  default: []

  CentOS-7:
  - java-latest-openjdk

  CentOS-8:
  - java-latest-openjdk

  Ubuntu:
  - openjdk-11-jdk

sys_packages: "{{ _sys_packages[ansible_distribution + '-' + ansible_distribution_major_version ] | d(_sys_packages[ansible_distribution]) | d(_sys_packages['default']) }}"
tls_packages: "{{ _tls_packages[ansible_distribution + '-' + ansible_distribution_major_version ] | d(_tls_packages[ansible_distribution]) | d(_tls_packages['default']) }}"
jdk_packages: "{{ _jdk_packages[ansible_distribution + '-' + ansible_distribution_major_version ] | d(_jdk_packages[ansible_distribution]) | d(_jdk_packages['default']) }}"

...