---

tls_base_path: /etc/tls/default

tls_cacerts_path: '{{ tls_base_path }}/cacerts'
tls_truststores_path: '{{ tls_base_path }}/truststores'

tls_cacert: '{{ tls_cacerts_path }}/{{ ansible_fqdn }}.ca'
tls_truststore: '{{ tls_truststores_path }}/{{ ansible_fqdn }}-truststore.jks'

tls_key_password: 'default'
tls_truststore_password: 'default'

tls_truststore_owner: root
tls_truststore_group: root

...