---

- name: Install packages
  when:
  - lookup('vars', 'install_' + item + '_packages') | bool
  - lookup('vars', item + '_packages') | length > 0
  ansible.builtin.package:
    name: "{{ lookup('vars', item + '_packages') }}"
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  loop:
  - 'sys'
  - 'tls'
  - 'jdk'

...