---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint */encrypt_private_keys*
  ansible-lint */encrypt_private_keys*

platforms:
- name: instance
  image: ${MOLECULE_DISTRO:-ubuntu:20.04}
  command: ${MOLECULE_COMMAND:-"sleep infinity"}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes

verifier:
  name: ansible

...