---

- name: Prepare
  hosts: all
  vars_files: ['../../roles/encrypt_private_keys/defaults/main.yml']

  pre_tasks:
  - name: gather os specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - "../../roles/encrypt_private_keys/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "../../roles/encrypt_private_keys/vars/{{ ansible_distribution }}.yml"
    tags: vars

  - name: Install system dependencies
    package:
      name: '{{ sys_packages }}'
      update_cache: yes
    changed_when: no
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: Install dependencies
    package: 
      name: '{{ tls_packages }}'
      update_cache: yes

  tasks:
  - name: Create certs dirs
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    loop:
    - '{{ tls_keys_path }}'

  - name: Gen private key
    community.crypto.openssl_privatekey:
      path: '{{ tls_key }}'

...