---

- name: Prepare
  hosts: all
  vars_files: ['../../roles/encrypt_private_keys/defaults/main.yml']

  tasks:
  - name: Update package cache
    package: update_cache=yes
    changed_when: no
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: Create certs dirs
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
      owner: '{{ tls_keystore_owner }}'
      group: '{{ tls_keystore_owner }}'
    loop:
    - '{{ tls_keys_path }}'

  - name: Gen private key
    community.crypto.openssl_privatekey:
      path: '{{ tls_key }}'

...