---

- name: Prepare
  hosts: all
  vars_files:
  - '../../roles/encrypt_private_keys/defaults/main.yml'

  tasks:
  - name: Install dependencies
    ansible.builtin.include_role:
      name: klusters.tls.packages

  - name: Create certs dirs
    ansible.builtin.file:
      path: "{{ tls_keys_path }}"
      state: directory
      mode: 0755

  - name: Gen private key
    community.crypto.openssl_privatekey:
      path: '{{ tls_key }}'

...