---

- name: Prepare
  hosts: all
  vars_files: ['../../roles/keystores/defaults/main.yml']

  tasks:
  - name: Update package cache
    package: update_cache=yes
    changed_when: no
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: '{{ tls_certs_path }}/{{ ansible_fqdn }}.csr'
      privatekey_path: '{{ tls_key }}'
      privatekey_passphrase: '{{ tls_keys_password }}'
      common_name: '{{ ansible_fqdn }}'

  - name: Generate a Self Signed OpenSSL certificate
    community.crypto.x509_certificate:
      path: '{{ tls_cert }}'
      privatekey_path: '{{ tls_key }}'
      privatekey_passphrase: '{{ tls_keys_password }}'
      csr_path: '{{ tls_certs_path }}/{{ ansible_fqdn }}.csr'
      provider: selfsigned

...