---

tls_base_path: /etc/tls

tls_certs_path: '{{ tls_base_path }}/certs'
tls_keys_path: '{{ tls_base_path }}/keys'
tls_jks_path: '{{ tls_base_path }}/java'
tls_p12_path: '{{ tls_base_path }}/pkcs12'

tls_cert: '{{ tls_keys_path }}/{{ ansible_fqdn }}.cert'
tls_key: '{{ tls_keys_path }}/{{ ansible_fqdn }}.key'
tls_jks_keystore: '{{ tls_keys_path }}/{{ ansible_fqdn }}.jks'
tls_p12_keystore: '{{ tls_keys_path }}/{{ ansible_fqdn }}.pkcs12'

tls_keys_password: 'default'
tls_jks_password: 'default'
tls_p12_password: 'default'

tls_keystore_owner: root
tls_keystore_group: root

...