---

galaxy_info:
  author: Klusters
  description: Install Cryptography packages needed by ansible to manage private keys, csr, certificates, pkcs12 and keystores / truststores
  company: ''
  license: GPL-2.0-or-later
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
    - 8
    - 7
  - name: Ubuntu
    versions:
    - xenial
    - bionic
  galaxy_tags:
  - system
  - tls

...