---

name: "klusters.tls.encrypt_private_keys"

on:
  push:
    paths:
      - 'roles/encrypt_private_keys/**'
      - 'molecule/encrypt_private_keys/**'
      - '.github/workflows/encrypt_private_keys.yml'
      - 'molecule/common/**'

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      MOLECULE_COMMAND: ${{ matrix.molecule_distro.command }}
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - { "distro":"centos:7" }
          - { "distro":"centos:8" }
          - { "distro":"ubuntu:18.04" }
          - { "distro":"ubuntu:20.04" }
        collection_role:
          - encrypt_private_keys
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          path: ansible_collections/klusters/tls

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] yamllint ansible-lint ansible

      - name: Run tests
        working-directory: ansible_collections/klusters/tls
        run: |
          molecule test -s ${{ matrix.collection_role }}
