---

name: "klusters.tls.encrypt_private_keys"

on:
  push:
    paths:
    - 'roles/encrypt_private_keys/**'
    - 'molecule/encrypt_private_keys/**'
    - '.github/workflows/encrypt_private_keys.yml'
    - 'molecule/common/**'
    tags_ignore:
      - '*'

jobs:
  molecule:
    runs-on: ubuntu-latest

    env:
      PY_COLORS: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      MOLECULE_COMMAND: ${{ matrix.molecule_distro.command }}
      
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
        - {'distro': 'centos:7'}
        - {'distro': 'centos:8'}
        - {'distro': 'ubuntu:18.04'}
        - {'distro': 'ubuntu:20.04'}
        collection_role:
        - encrypt_private_keys

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ansible_collections/klusters/tls

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Cache python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/python_requirements.txt') }}

    - name: Install python packages
      working-directory: ansible_collections/klusters/tls
      run: |
        (test -f molecule/${{ matrix.collection_role }}/python_requirements.txt && pip install --upgrade --upgrade-strategy eager -r molecule/${{ matrix.collection_role }}/python_requirements.txt ) ||
        (test -f molecule/common/python_requirements.txt && pip install --upgrade --upgrade-strategy eager -r molecule/common/python_requirements.txt )

    - name: Build and Install the collection
      working-directory: ansible_collections/klusters/tls
      run: |
        collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
        ansible-galaxy collection install $collection_file

    - name: Run tests
      working-directory: ansible_collections/klusters/tls
      run: |
        molecule test -s ${{ matrix.collection_role }}

...
