---

name: "klusters.tls.keystores"

on:
  push:
    paths:
    - 'roles/keystores/**'
    - 'molecule/keystores/**'
    - '.github/workflows/keystores.yml'
    - 'molecule/common/**'

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      MOLECULE_COMMAND: ${{ matrix.molecule_distro.command }}
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
        - { "distro":"centos:7" }
        - { "distro":"centos:8" }
        - { "distro":"ubuntu:18.04" }
        - { "distro":"ubuntu:20.04" }
        collection_role:
        - keystores
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ansible_collections/klusters/tls

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Cache python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('molecule/common/python_requirements.txt') }}

    - name: Install python packages
      working-directory: ansible_collections/klusters/tls
      run: |
        pip install --upgrade --upgrade-strategy eager -r molecule/common/python_requirements.txt

    - name: Run tests
      working-directory: ansible_collections/klusters/tls
      run: |
        molecule test -s ${{ matrix.collection_role }}

...