---

- name: Get vars from item if in a loop
  when: outer_item is defined
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  loop: '{{ outer_item | dict2items }}'
  no_log: yes

- name: Create keys dir
  ansible.builtin.file:
    path: '{{ tls_keys_path }}'
    state: directory
    mode: 0755

- name: Get information on encrypted key
  community.crypto.openssl_privatekey_info:
    path: '{{ tls_key_encrypted }}'
    passphrase: '{{ tls_key_password }}'
  register: encrypted_key
  failed_when: no

- name: Get information on plain key
  community.crypto.openssl_privatekey_info:
    path: '{{ tls_key }}'
  register: plain_key

- name: Generate encrypted private key only if different
  when: 
  - encrypted_key.public_key is not defined or
    encrypted_key.public_key != plain_key.public_key
  block: 
  - name: Backup private key
    ansible.builtin.copy:
      remote_src: yes
      src: '{{ tls_key }}'
      dest: '{{ tls_key_encrypted }}'
      mode: 0600

  - name: Encrypt private key
    ansible.builtin.command: "ssh-keygen -m PEM -t rsa -f '{{ tls_key_encrypted }}' -p -N '{{ tls_key_password }}'"

...