---

- name: Get vars from item if in a loop
  set_fact:
    '{{ item.key }}': '{{ item.value }}'
  loop: '{{ outer_item | dict2items }}'
  when: outer_item
  no_log: yes

- name: Create certs dir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: '{{ tls_keystore_owner }}'
    group: '{{ tls_keystore_owner }}'
  loop:
  - '{{ tls_certs_path }}'
  - '{{ tls_keys_path }}'
  - '{{ tls_jks_path }}'
  - '{{ tls_p12_path }}'

- name: Backup private key
  ansible.builtin.copy:
    remote_src: yes
    src: '{{ tls_key }}'
    dest: '{{ tls_key_encrypted }}'
    mode: 0600

- name: Encrypt private key
  ansible.builtin.command: "ssh-keygen -m PEM -t rsa -f '{{ tls_key_encrypted }}' -p -N '{{ tls_keys_password }}'"

...