---

- name: Get vars from item if in a loop
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  loop: '{{ outer_item | dict2items }}'
  when: outer_item is defined
  no_log: yes

- name: Create certs dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: '{{ tls_keystore_owner }}'
    group: '{{ tls_keystore_group }}'
  loop:
  - '{{ tls_certs_path }}'
  - '{{ tls_keys_path }}'
  - '{{ tls_keystore_path }}'

- name: Create Java keystore from cert and private_key
  community.general.java_keystore:
    name: '{{ tls_keystore_alias }}'
    certificate_path: '{{ tls_cert }}'
    private_key_path: '{{ tls_key_encrypted }}'
    private_key_passphrase: '{{ tls_key_password }}'
    password: '{{ tls_keystore_password }}'
    dest: '{{ tls_keystore }}'
    owner: '{{ tls_keystore_owner }}'
    group: '{{ tls_keystore_group }}'
    keystore_type: jks

...