---

- name: Get vars from item if in a loop
  set_fact:
    '{{ item.key }}': '{{ item.value }}'
  loop: '{{ outer_item | dict2items }}'
  when: outer_item is defined
  no_log: yes

- name: Create certs dir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: '{{ tls_keystore_owner }}'
    group: '{{ tls_keystore_group }}'
  loop:
  - '{{ tls_certs_path }}'
  - '{{ tls_keys_path }}'
  - '{{ tls_jks_path }}'
  - '{{ tls_p12_path }}'

- name: Create PKCS12 (Ansible <2.7)
  command: "openssl pkcs12 -export -out '{{ tls_p12_keystore }}' -inkey '{{ tls_key_encrypted }}' -in '{{ tls_cert }}' -passin pass:'{{ tls_key_password }}' -passout pass:'{{ tls_p12_password }}'"

- name: Import pkcs12 keystore in a java keystore
  java_cert:
    pkcs12_path: '{{ tls_p12_keystore }}'
    pkcs12_password: '{{ tls_p12_password }}'
    cert_alias: '{{ ansible_fqdn }}'
    pkcs12_alias: '{{ ansible_fqdn }}'
    keystore_path: '{{ tls_jks_keystore }}'
    keystore_pass: '{{ tls_jks_keystore_password }}'
    keystore_create: yes
    state: present

...