---

- name: Get vars from item if in a loop
  set_fact:
    '{{ item.key }}': '{{ item.value }}'
  loop: '{{ outer_item | dict2items }}'
  when: outer_item is defined
  no_log: yes

- name: Create certs dir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: '{{ tls_keystore_owner }}'
    group: '{{ tls_keystore_group }}'
  loop:
  - '{{ tls_certs_path }}'
  - '{{ tls_keys_path }}'
  - '{{ tls_jks_path }}'
  - '{{ tls_p12_path }}'

- name: Generate pkc12 keystore from cert and private_key
  openssl_pkcs12:
    action: export
    path: '{{ tls_p12_keystore }}'
    passphrase: '{{ tls_p12_password }}'
    friendly_name: '{{ ansible_fqdn }}'
    certificate_path: '{{ tls_cert }}'
    privatekey_path:  '{{ tls_key_encrypted }}'
    privatekey_passphrase: '{{ tls_keys_password }}'
    owner: '{{ tls_keystore_owner }}'
    group: '{{ tls_keystore_group }}'
    state: present

- name: Import pkcs12 keystore in a java keystore
  java_cert:
    pkcs12_path: '{{ tls_p12_keystore }}'
    pkcs12_password: '{{ tls_p12_password }}'
    cert_alias: '{{ ansible_fqdn }}'
    pkcs12_alias: '{{ ansible_fqdn }}'
    keystore_path: '{{ tls_jks_keystore }}'
    keystore_pass: '{{ tls_jks_password }}'
    keystore_create: yes
    state: present

...